import 'tailwindcss/tailwind.css'
import '../components/global/global.css'

export const metadata = {
  title: 'INFLUXED Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
